#!/bin/bash

steamargs=("-steamos3" "-steampal" "-steamdeck" "-gamepadui")
if [[ -x $HOME/devkit-game/devkit-steam ]]; then
	# Start Apollo and netstickd services for network streaming and 3DS compatibility.
	systemctl --user start apollo.service &
	systemctl --user start netstickd.service &
	exec "$HOME"/devkit-game/devkit-steam "${steamargs[@]}"
else
	# Start Apollo and netstickd services for network streaming and 3DS compatibility.
	systemctl --user start apollo.service &
	systemctl --user start netstickd.service &
	exec steam "${steamargs[@]}"
fi
