#!/bin/bash
set -e

# Get the current logged-in user (not root) (thanks mall0x!)
CURRENT_USER=$(logname 2>/dev/null || whoami)
DISPLAY_MANAGER="$(systemctl show -p Id --value display-manager)"
case "${DISPLAY_MANAGER%.service}" in
    gdm) CONF_FILE="/var/lib/AccountsService/users/${CURRENT_USER}";;
esac

# Don't do anything if system is using unsupported display manager
[[ -z "$CONF_FILE" ]] && exit 0

# Session, gamescope or gnome
SESSION="${1:-gamescope-session}"

if [[ ! -d "$(dirname "$CONF_FILE")" ]]; then
    mkdir -p "$(dirname "$CONF_FILE")"
fi

# Use sed to avoid destructive changes to AccountService file
PREV_SESSION=$(cat $CONF_FILE | grep -o -P '(?<=Session=).*')
sed -i -e '0,/'"$PREV_SESSION"'/{s/'"$PREV_SESSION"'/'"$SESSION"'/g}' $CONF_FILE;
